// AI-vs-baseline evaluation of duplicate detection against the seed set's
// known answers. Run with:  npm run evaluate
//
// Every seed ticket in data/tickets.json carries a hand-assigned `cluster`
// label (e.g. "vpn", "lockout"), or null for standalone tickets. Two
// tickets are a TRUE duplicate pair when they share a cluster. Each
// method scores all 190 ticket pairs; a pair is PREDICTED duplicate when
// its score is at or above the method's threshold. We then report
// precision, recall and F1 for each method, a sweep across thresholds,
// and the closest false positives / weakest true pairs - the cases worth
// discussing in the report.
//
// Then a HELD-OUT test: data/eval-holdout.json holds 12 tickets written
// after the thresholds were chosen and never used for tuning. Each is run
// as a "new ticket" against the 20 seed tickets at the FIXED configured
// thresholds - this is the fairer number to quote.
//
// Writes the full results to docs/evaluation-results.md as well.
//
// Needs LLM_API_KEY for the AI method (embeddings are cached in
// data/.embedding-cache.json, so re-runs cost nothing). Without a key it
// evaluates the baseline only.

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { seedTickets } = require('../lib/seedData');
const embeddings = require('../lib/embeddings');
const { cosineSimilarity, tokenize, jaccardSimilarity } = require('../lib/similarity');
const { aiThreshold, baselineThreshold } = require('../lib/duplicates');

const holdout = JSON.parse(fs.readFileSync(path.join(__dirname, '../data/eval-holdout.json'), 'utf8'));
const raw = JSON.parse(fs.readFileSync(path.join(__dirname, '../data/tickets.json'), 'utf8'));
const clusterOf = Object.fromEntries(raw.map((t) => [t.ticketId, t.cluster]));
const tickets = seedTickets();

function allPairs(scoreFn) {
  const pairs = [];
  for (let i = 0; i < tickets.length; i++) {
    for (let j = i + 1; j < tickets.length; j++) {
      const a = tickets[i];
      const b = tickets[j];
      pairs.push({
        a: a.ticketId,
        b: b.ticketId,
        truth: !!clusterOf[a.ticketId] && clusterOf[a.ticketId] === clusterOf[b.ticketId],
        score: scoreFn(i, j),
      });
    }
  }
  return pairs;
}

function metrics(pairs, threshold) {
  let tp = 0;
  let fp = 0;
  let fn = 0;
  pairs.forEach((p) => {
    const predicted = p.score >= threshold;
    if (predicted && p.truth) tp += 1;
    else if (predicted && !p.truth) fp += 1;
    else if (!predicted && p.truth) fn += 1;
  });
  const precision = tp + fp ? tp / (tp + fp) : 0;
  const recall = tp + fn ? tp / (tp + fn) : 0;
  const f1 = precision + recall ? (2 * precision * recall) / (precision + recall) : 0;
  return { threshold, tp, fp, fn, precision, recall, f1 };
}

const pct = (x) => `${(x * 100).toFixed(0)}%`;
const fmt = (m) =>
  `| ${m.threshold.toFixed(2)} | ${m.tp} | ${m.fp} | ${m.fn} | ${pct(m.precision)} | ${pct(m.recall)} | ${m.f1.toFixed(2)} |`;

function sweep(pairs, from, to, step) {
  const rows = [];
  for (let t = from; t <= to + 1e-9; t += step) rows.push(metrics(pairs, Math.round(t * 100) / 100));
  return rows;
}

function titleOf(id) {
  return tickets.find((t) => t.ticketId === id).title;
}

function section(name, pairs, threshold, sweepRange) {
  const lines = [];
  const m = metrics(pairs, threshold);
  const best = sweep(pairs, ...sweepRange).reduce((x, y) => (y.f1 > x.f1 ? y : x));
  lines.push(`## ${name}`, '');
  lines.push(`At the configured threshold **${threshold}**: precision ${pct(m.precision)}, recall ${pct(m.recall)}, F1 ${m.f1.toFixed(2)} (TP ${m.tp}, FP ${m.fp}, FN ${m.fn}).`);
  lines.push(`Best F1 on this set: **${best.f1.toFixed(2)}** at threshold ${best.threshold}.`, '');
  lines.push('| Threshold | TP | FP | FN | Precision | Recall | F1 |', '|---|---|---|---|---|---|---|');
  sweep(pairs, ...sweepRange).forEach((r) => lines.push(fmt(r)));
  const falsePos = pairs.filter((p) => !p.truth).sort((x, y) => y.score - x.score).slice(0, 5);
  const weakTrue = pairs.filter((p) => p.truth).sort((x, y) => x.score - y.score).slice(0, 5);
  lines.push('', '**Highest-scoring NON-duplicate pairs** (closest to being false positives):', '');
  falsePos.forEach((p) => lines.push(`- ${p.score.toFixed(3)} - ${p.a} "${titleOf(p.a)}" vs ${p.b} "${titleOf(p.b)}"`));
  lines.push('', '**Lowest-scoring TRUE duplicate pairs** (hardest to catch):', '');
  weakTrue.forEach((p) => lines.push(`- ${p.score.toFixed(3)} - ${p.a} "${titleOf(p.a)}" vs ${p.b} "${titleOf(p.b)}"`));
  lines.push('');
  return { lines, m, best };
}

async function main() {
  const truePairs = allPairs(() => 0).filter((p) => p.truth).length;
  const out = [
    '# Duplicate detection: AI vs. baseline',
    '',
    `Generated by \`npm run evaluate\` on ${new Date().toISOString().slice(0, 10)}.`,
    `${tickets.length} seed tickets, ${(tickets.length * (tickets.length - 1)) / 2} pairs, ${truePairs} true duplicate pairs (same \`cluster\` label in data/tickets.json).`,
    '',
  ];

  const tokens = tickets.map((t) => tokenize(`${t.title} ${t.description}`));
  const baselinePairs = allPairs((i, j) => jaccardSimilarity(tokens[i], tokens[j]));
  const base = section('Baseline: keyword Jaccard', baselinePairs, baselineThreshold(), [0.1, 0.4, 0.05]);
  out.push(...base.lines);

  const result = await embeddings.embedTexts(tickets.map(embeddings.ticketText));
  let ai = null;
  if (result.status === 'ok') {
    const v = result.vectors;
    const aiPairs = allPairs((i, j) => cosineSimilarity(v[i], v[j]));
    ai = section(`AI: embeddings + cosine (${result.model})`, aiPairs, aiThreshold(), [0.6, 0.9, 0.02]);
    out.push(...ai.lines);
  } else {
    out.push('## AI: embeddings + cosine', '', `Not evaluated: ${result.reason}.`, '');
  }

  // ---- Held-out test at fixed thresholds ----
  out.push('## Held-out test (fixed thresholds, no tuning)', '');
  out.push(`${holdout.length} new tickets, each compared against the ${tickets.length} seed tickets. Pair-level scores over ${holdout.length * tickets.length} pairs; "top match right" = the highest-scoring flagged match is in the expected cluster; "false alarm" = a ticket with no real duplicate got at least one match flagged.`, '');
  const holdTokens = holdout.map((h) => tokenize(`${h.title} ${h.description}`));
  const holdResult = result.status === 'ok' ? await embeddings.embedTexts(holdout.map(embeddings.ticketText)) : null;
  const holdRows = [];
  function holdoutEval(name, threshold, scoreFn) {
    const pairs = [];
    let topRight = 0;
    let withCluster = 0;
    let falseAlarms = 0;
    let noCluster = 0;
    const perTicket = [];
    holdout.forEach((h, i) => {
      const scored = tickets.map((t, j) => ({ id: t.ticketId, score: scoreFn(i, j), truth: !!h.expectedCluster && clusterOf[t.ticketId] === h.expectedCluster }));
      scored.forEach((s) => pairs.push(s));
      const flagged = scored.filter((s) => s.score >= threshold).sort((a, b) => b.score - a.score);
      if (h.expectedCluster) {
        withCluster += 1;
        if (flagged[0] && flagged[0].truth) topRight += 1;
      } else {
        noCluster += 1;
        if (flagged.length) falseAlarms += 1;
      }
      perTicket.push(`${flagged.length ? flagged.slice(0, 3).map((f) => `${f.id}${f.truth ? '' : ' (wrong)'} ${f.score.toFixed(2)}`).join(', ') : 'no matches'}`);
    });
    const m = metrics(pairs, threshold);
    holdRows.push({ name, perTicket });
    out.push(`- **${name}** @ ${threshold}: precision ${pct(m.precision)}, recall ${pct(m.recall)}, F1 ${m.f1.toFixed(2)}; top match right ${topRight}/${withCluster}; false alarms ${falseAlarms}/${noCluster}`);
    return { m, topRight, withCluster, falseAlarms, noCluster };
  }
  const holdBase = holdoutEval('Baseline', baselineThreshold(), (i, j) => jaccardSimilarity(holdTokens[i], tokens[j]));
  let holdAi = null;
  if (holdResult && holdResult.status === 'ok') {
    holdAi = holdoutEval('AI', aiThreshold(), (i, j) => cosineSimilarity(holdResult.vectors[i], result.vectors[j]));
  }
  out.push('', '| Held-out ticket | Expected | ' + holdRows.map((r) => r.name).join(' | ') + ' |', '|---|---|' + holdRows.map(() => '---|').join(''));
  holdout.forEach((h, i) => out.push(`| ${h.title} | ${h.expectedCluster || '(none)'} | ${holdRows.map((r) => r.perTicket[i]).join(' | ')} |`));
  out.push('');

  out.push(
    '## Caveats',
    '',
    '- 20 tickets is a small, hand-made set. Treat these numbers as a sanity check of the approach, not as a general accuracy claim.',
    '- The thresholds were tuned on this same set, so the "best F1" figures are optimistic. A fair test needs fresh tickets written after the thresholds were fixed.',
    '- "Duplicate" here means same underlying issue. T-1019 (office wifi dropping) is deliberately close to the VPN cluster but labelled standalone: it is a hard negative.',
    ''
  );

  const file = path.join(__dirname, '../docs/evaluation-results.md');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, out.join('\n'));

  console.log(`Baseline  @${base.m.threshold}: P ${pct(base.m.precision)} R ${pct(base.m.recall)} F1 ${base.m.f1.toFixed(2)} (best F1 ${base.best.f1.toFixed(2)} @${base.best.threshold})`);
  if (ai) console.log(`AI        @${ai.m.threshold}: P ${pct(ai.m.precision)} R ${pct(ai.m.recall)} F1 ${ai.m.f1.toFixed(2)} (best F1 ${ai.best.f1.toFixed(2)} @${ai.best.threshold})`);
  else console.log(`AI        not evaluated: ${result.reason}`);
  const hl = (name, h) => console.log(`${name} held-out: P ${pct(h.m.precision)} R ${pct(h.m.recall)} F1 ${h.m.f1.toFixed(2)}, top match right ${h.topRight}/${h.withCluster}, false alarms ${h.falseAlarms}/${h.noCluster}`);
  hl('Baseline', holdBase);
  if (holdAi) hl('AI      ', holdAi);
  console.log(`Full results written to ${path.relative(process.cwd(), file)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
